### PR TITLE
Document how to make tty available at UART

### PR DESCRIPTION
**Pull request by geonnave**
The documentation I've found on how to do this was a little sparse, so I think adding it here may help other people needing this in the future.

Oh, one thing I would like to ask: is it possible to enable the rpi-specific config *only if* the target is an rpi? If yes, I can update the section with such new information.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks. This is definitely useful. Although we've normally been overriding the `erlinit.config` to set this option rather than change `fwup.conf`. I think that will be a little easier since it is just one file that needs to change. https://hexdocs.pm/nerves/advanced-configuration.html#root-filesystem-additions.

As for your question, I'm not sure that I understand. `nerves_system_rpi` will only boot on RPi Zeros, Model A+ and Model B+'s. You'll get the rainbow screen on the others.

**Comment by geonnave** [comment]
Oh, I didn't know I could do that; it is easier indeed, thanks. Just a question: how should I put the tty configuration in the `erlinit.config`?

About my question, I could not test it yet on a board but I *think* I've got it solved with 
```
if System.get_env("NERVES_TARGET") == "rpi" do
  config :nerves, :firmware,
    fwup_conf: "config/fwup_rpi.conf"
end
```

**Comment by GregMefford** [comment]
@geonnave thanks for writing this up! I'm wondering if we should document this here in the `rpi` system, and for consistency, in each of the other system repos. I included this in my recently-proposed FAQ on the main Nerves project repo, but maybe it should be integrated somewhere 'more official' that the FAQ could link to.

**Comment by GregMefford** [comment]
To clarify, I think the procedure in general isn't specific to the `rpi` target, only the particular tty device name is. Maybe there should be a central how-to for it rather than duplicating it in each system's documentation.

**Comment by geonnave** [comment]
@GregMefford excellent, an official guide would be nice, but the FAQ seems to be a good place to start!

**Comment by fhunleth** [comment]
@geonnave Here's how I used to structure my `erlinit.config` files to make it easy to switch where the terminal comes out: https://github.com/fhunleth/nerves_presenter/blob/master/apps/fw/config/rootfs-additions/etc/erlinit.config#L9-L10. Somewhere along the line it got dropped, but I think that it answers your question about how to add it to the file.

**Comment by geonnave** [comment]
@fhunleth It really answers, thank you!

**Comment by geonnave** [comment]
[This FAQ pull request, #37](https://github.com/nerves-project/nerves/pull/37), now includes the `erlinit.config` solution for the original problem that motivated this PR (among other answers). Given this I'm closing this pull request.

**Comment by GregMefford** [comment]
@fhunleth as I was writing the FAQ answer, I noticed that the file probably used to be structured like that. I'm not sure why they got removed, but I was thinking about doing a PR for each of them to standardize this for all of them. I think there's some other minor tweaks/standardization a that I could roll into a PR for each repo.

**Comment by fhunleth** [comment]
@GregMefford That seems like a good idea to me.

**Pull request closed without merging**
