### PR TITLE
Hardware ExUnit Tests

### PR DESCRIPTION
**Pull request by mobileoverlord**
More info can be found on the rpi0 repo
nerves-project/nerves_system_rpi0#20

### CODE REVIEW

**Comment by mobileoverlord** [comment]
Moved test firmware project to `test` directory. This is ready for review.

**Comment by fhunleth** [comment]
This looks copy/paste from rpi0. Are there any differences other than a couple rpi0->rpi renames?

**Comment by mobileoverlord** [comment]
rpi0 -> rpi
wlan0 -> eth0
Provisioning text is shorter since we don't need to do much of anything besides plug it in

**Comment by fhunleth** [comment]
Sweet! 

p.s. it would be great to have a regression test hack night or two for the systems. There are so many relatively easy things that people could contribute that would majorly help me to have when doing the impending RPi* Linux 4.9 update. Maybe we could organize an event post-ElixirConf. It would be a great way of getting new people involved in a way that would have an immediate practical impact. I could submit a long list of tests that I'd like for system validation to make sure that no one would be bored.

**Pull request merged**
